### ISSUE TITLE
Deprecate numbered running header (\h#)

### ISSUE THREAD

**Issue by klassenjm** [ubsicap/usfm#21]
## Proposal

* Deprecate the numbered forms of paragraph marker `\h#`. Retain only `\h`.

A companion USX 3.0 proposal exists at: ubsicap/usx#15

#### Details

The optional number variable in `\h#` was intended to represent different components or even levels of text required for a header presentation.

In practice, specific content for different header positions is highly variable, and typically a publication level decision. `\h`, `\toc1`, `\toc2`, `\toc3`, and Paratext's Scripture Reference Settings are sufficient generic metadata to supply most metadata needed for generating header texts. Other features for composing customized headers are also available in publishing tools such as Publishing Assistant (e.g. get first or last section heading on a page).

**Comment by cmahte** [comment]
How long will this stay deprecated before becoming obsolete?  I rely on the variant \h tags for positional header info into standardized templates: 

Odd page head (inside h5 , center h1, outside h3)
Even page head (inside h4, center h0, outside h2)
Odd page tail (inside/center h7, ouside h9)
Even page tail (inside/center h6, outside h8)

The missing block is for the page number, which doesn't require a running head variable.

I have no problem with \h# being deprecated indefinitely, but would like to avoid obsolete status, because those tags cause import into standard USFM tools to fail.
